resolver: ghc-7.10.2

packages:
- '.'

extra-deps:
- convertible-1.1.1.0
- freenect-1.2.1
- friday-0.2.2.0
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- primitive-0.6.1.0
- ratio-int-0.1.2
- text-1.2.1.3
- vector-0.11.0.0
